### ISSUE TITLE
Contanki does not work for me after 10/23/22 update

### ISSUE THREAD

**Issue by Lou-Rye** [roxgib/anki-contanki#26]
I updated it, and now it doesn't work for me anymore (the Controller option no longer appears under Tools, even when my controller is on). For reference, I use a Windows laptop.

This is the message everytime I try to press a button on my controller:

Error

An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.

If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.

When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.

Debug info:

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1

Platform: Windows 10

Flags: frz=True ao=True sv=2

Add-ons, last update check: 2022-10-23 05:41:24

Caught exception:

Traceback (most recent call last):

File "aqt.webview", line 42, in cmd

File "aqt.webview", line 149, in _onCmd

File "aqt.webview", line 618, in _onBridgeCmd

File "aqt.hooks_gen", line 4358, in __call__

File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 117, in on_receive_message

funcs[func](*args)

File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 320, in on_connect

_controller = identify_controller(

File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1898790263\controller.py", line 122, in identify_controller

vendor_id, device_id = parse_controller_id(id_)

File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1898790263\controller.py", line 105, in parse_controller_id

return (vendor_id.lower(), device_id.lower())

AttributeError: 'NoneType' object has no attribute 'lower'

Looking for a way to fix this as this was a huge QoL change; thanks!

**Comment by roxgib** [comment]
Thanks for reporting this, it has been fixed with [8902c91](https://github.com/roxgib/anki-contanki/commit/8902c91c60abf7eed356a7e1f20e39ac2bfbfc82) and a new beta should be out soon.

**Comment by Lou-Rye** [comment]
> Thanks for reporting this, it has been fixed with [8902c91](https://github.com/roxgib/anki-contanki/commit/8902c91c60abf7eed356a7e1f20e39ac2bfbfc82) and a new beta should be out soon.

Thank you so much! However, I just updated it, and I am still getting the same message (I made sure to close and reopen Anki for the changes to take effect).
This is the error message I am getting:
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-24 08:25:58

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 123, in on_receive_message
    funcs[func](*args)
  File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 329, in on_connect
    _controller = identify_controller(
  File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1898790263\controller.py", line 134, in identify_controller
    device_name = controller_ids["devices"][vendor_id][device_id]
KeyError: None

Can this be fixed? I'd appreciate if it could! Thanks again
