### ISSUE TITLE
Display/config issue on Windows

### ISSUE THREAD

**Issue by roxgib** [roxgib/anki-contanki#5]
https://forums.ankiweb.net/t/new-add-on-contanki-controller-support-for-anki/18925/4

I haven't been able to reproduce this so far, next step is to try with a few different Windows machines.

**Comment by roxgib** [comment]
[User reports this is now resolved](https://forums.ankiweb.net/t/new-add-on-contanki-controller-support-for-anki/18925/8?u=roxgib)

**Comment by khonkhortisan** [comment]
This issue is not resolved
Incompatibility with Dark title bars for windows https://ankiweb.net/shared/info/1718996340
Both contanki and darktitlebars must be enabled for the issue to appear, any other addons being enabled doesn't affect it.

**Comment by roxgib** [comment]
That sounds like it might be an unrelated issue. Can you tell me what happens when you have both enabled?

**Comment by khonkhortisan** [comment]
contanki 
![imagen](https://user-images.githubusercontent.com/1996449/185822803-9cc33780-20dc-4137-95a7-adcfbb045dae.png)
contanki+LT
![imagen](https://user-images.githubusercontent.com/1996449/185823565-e30a697c-6358-4e8d-a84b-68c7c6389550.png)
contanki+darktitlebars
![imagen](https://user-images.githubusercontent.com/1996449/185823380-e587fd6a-71dc-47ea-b078-67f013fcc897.png)
contanki+darktitlebars+LT
![imagen](https://user-images.githubusercontent.com/1996449/185823398-5e52cc9e-235d-4cb9-a504-1bc31369dd45.png)
