### ISSUE TITLE
Can't use quick connect. 8bitdo micro X mode. Mac OS

### ISSUE THREAD

**Issue by AnKingMed** [roxgib/anki-contanki#78]
I have the following settings and I've tried all three options to do action. When I select the quick select, it just does whatever the action of that D pad direction is normally, not the quick select one.  I've tried removing the actions for that D pad direction, but it still doesn't work. I can't do any of the quick actions

A suggestion as well: many of us hold the 8bitdo controller sideways for one handed review so it'd be nice to be able to rotate the quick connect so that it works with that direction scheme. not the biggest deal, just a quality of life thing.

![image](https://github.com/roxgib/anki-contanki/assets/57678116/03412a09-ec63-402d-8214-be4edf6fab5f)

p.s. working on a web page (currently just on notion but it'll be official) at www.theanking.com/controller that will have a tutorial on using this addon with the 8bitdo controllers as they seem to be the most popular

**Comment by roxgib** [comment]
This one has been puzzling me, but it should now be fixed with ccc8a85.

**Comment by roxgib** [comment]
Should be fixed in today's update

**Comment by AnKingMed** [comment]
This still isn't working for me. In D mode I can bring up quick select, but the D pad doesn't do anything. In X mode, I can bring up quick select and then select a direction and it will highlight the one I selected, but won't actually do that action.

I don't know if this matters but I noticed that it shows up twice in the tools menu.  One of them it can't find, the other it is connected to. Might just be my setup
![image](https://github.com/roxgib/anki-contanki/assets/57678116/46c938c9-0b13-4397-92c2-ae020d25bdad)
